# Generated by Django 4.0.3 on 2022-04-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
